server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jie12366/spring_cloud_demo   # 配置git仓库
          search-paths: config-repo                            # git仓库下的目录
          username: 2263509062@qq.com                           # git账号
          password: xiongyijie123456                            # git密码
    bus:
      trace:
        enabled: true # 开启消息跟踪
  security:
    user:
      name: monJay
      password: pwd
  rabbitmq:
    host: localhost
    port: 5672
    username: monJay
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka